version: '3'
env_file: .env
services:
  wireguard:
    container_name: 'wireguard'
    build: .
    privileged: true
    restart: 'unless-stopped'
    sysctls:
      - "net.ipv4.conf.all.rp_filter=2"
      - "net.ipv6.conf.all.disable_ipv6=0"
    ports:
      - 51413:51413
      - 51413:51413/udp
      - 51820:51820/udp
      - 9091:9091
    volumes:
      - /etc/wireguard-docker:/etc/wireguard
  transmission:
    image: 'linuxserver/transmission'
    container_name: 'transmission'
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/transmission-web-control/ #optional
      - USER=username #optional
      - PASS=password #optional
    volumes:
      - /path/to:/config
      - /path/to:/downloads
      - /path/to:/watch
    restart: unless-stopped
    network_mode: "service:wireguard"
